---
title: Arizona Tri-University Recharge and Water Reliability Project (ATUR-WRP)
date: "10/16/24"
---

test
## About

Escalating drought over the past two decades has led to growing concerns regarding water quantity and quality for Arizona’s communities. At the request of the Arizona Department of Water Resources, a team of researchers from the University of Arizona (UArizona), Arizona State University (ASU), and Northern Arizona University (NAU) will study locations and methods for protecting and enhancing groundwater recharge across the state.

More than 90% of precipitation that falls as rain and snow in Arizona evaporates before it enters a stream or recharges the groundwater.
Capturing this water before it escapes to the atmosphere and encouraging it to percolate into the ground to replenish aquifers (enhanced recharge) can increase water supplies for communities and support ecosystems



**To Learn more about this project and access project resources click on the [Wiki Tab](https://github.com/Ryan3Lima/ATUR-WIKI/wiki) of this repository.**

Our goal is to create data which is ethical, reproducable, and collaborate: To learn more about the template we chose to follow see [The Turing Way](https://book.the-turing-way.org/index.html)
